apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-api
  namespace: recommendations
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-api
  template:
    metadata:
      labels:
        app: recommendation-api
    spec:
      serviceAccountName: recommendations-sa
      containers:
        - name: api
          image: ghcr.io/rajesh-proddu/videostreamingplatform-recommendations/recommendations:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: recommendation-config
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
